
  name: knx-firewall
  version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
  summary: knx firewall is a simple fork of nx-firewall: |
    KNX Firewall is a firewall tool for Linux uses the Qt toolkit.
    You can use the wizard to create a basic firewall, then streamline it further using the dynamic rules.
    KNX Firewall is an open source application that provides users with a graphical user interface (GUI) for the ufw (Uncomplicated Firewall)/iptables command-line interface, can open and close ports with a few clicks, or monitor your services giving access only to a select few.
    This tool was created by the folks at https://nxos.org/

  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  parts:
    my-part:
      # See 'snapcraft plugins'
      plugin: nil
  
